packages:
  - 'packages/devtool-plugin-cli'
  - 'packages/devtool-plugin-core'
  - 'packages/devtools-frontend-lynx'
  - 'packages/lynx-devtool-cli'
  - 'packages/lynx-devtool-utils'
  - 'packages/devtools-web-simulator'
  - 'src'
