// Copyright 2025 The Lynx Authors. All rights reserved.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.

export const PLUGIN_EVENT_ASYNC_BRIDGE = 'PLUGIN_EVENT_ASYNC_BRIDGE';
export const PLUGIN_EVENT_SWITCH_VIEW = 'PLUGIN_EVENT_SWITCH_VIEW';
export const PLUGIN_EVENT_SELECTOR_CHANGED = 'PLUGIN_EVENT_SELECTOR_CHANGED';
export const PLUGIN_EVENT_PLUGIN_CHANGED = 'PLUGIN_EVENT_PLUGIN_CHANGED';
export const PLUGIN_EVENT_PLUGIN_CREATED = 'PLUGIN_EVENT_PLUGIN_CREATED';
export const PLUGIN_EVENT_SHOW = 'PLUGIN_EVENT_SHOW';
export const PLUGIN_EVENT_SHOW_MODAL = 'PLUGIN_EVENT_SHOW_MODAL';
export const PLUGIN_EVENT_MODAL_SHOW = 'PLUGIN_EVENT_MODAL_SHOW';
export const PLUGIN_EVENT_GET_ALL_PLUGINS = 'PLUGIN_EVENT_GET_ALL_PLUGINS';
export const PLUGIN_EVENT_GET_PLATFORM_PLUGINS = 'PLUGIN_EVENT_GET_PLATFORM_PLUGINS';
export const PLUGIN_EVENT_CUSTOM_EVENT = 'PLUGIN_EVENT_CUSTOM_EVENT';
export const PLUGIN_EVENT_ENV_LOG = 'PLUGIN_EVENT_ENV_LOG';
export const PLUGIN_EVENT_CUSTOM_EVENT_RESPONSE = 'PLUGIN_EVENT_CUSTOM_EVENT_RESPONSE';

export const CONFIG_EVENT_GET_CONFIG = 'CONFIG_EVENT_GET_CONFIG';
export const CONFIG_EVENT_SET_CONFIG = 'CONFIG_EVENT_SET_CONFIG';

export const SIMULATOR_EVENT_BACK = 'SIMULATOR_EVENT_BACK';
export const SIMULATOR_EVENT_FORWARD = 'SIMULATOR_EVENT_FORWARD';
export const SIMULATOR_EVENT_REFRESH = 'SIMULATOR_EVENT_REFRESH';
export const SIMULATOR_EVENT_OPEN_SCHEME = 'SIMULATOR_EVENT_OPEN_SCHEME';

export const UPDATER_EVENT_DOWNLOAD_PROGRESS = 'UPDATER_EVENT_DOWNLOAD_PROGRESS';
